Repository uiowaSEP2025/sep2025-project-team_006, pull requests merged in 2025-03, with the labels that each got.

#12 Faculty Metrics API Calls
  backend/__tests__/faculty-metrics.controller.spec.ts
  backend/__tests__/faculty-metrics.service.spec.ts
  backend/__tests__/http_exception.filter.spec.ts
  backend/__tests__/response.interceptor.spec.ts
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/config/http_exception.filter.ts
  backend/src/config/response.interceptor.ts
  backend/src/dto/create-faculty-metric.dto.ts
  backend/src/dto/update-faculty-metric.dto.ts
  backend/src/entity/faculty.entity.ts
  backend/src/entity/student.entity.ts
  backend/src/main.ts
  backend/src/modules/faculty-metrics/faculty-metrics.controller.ts
  backend/src/modules/faculty-metrics/faculty-metrics.module.ts
  backend/src/modules/faculty-metrics/faculty-metrics.service.ts
  backend/src/seed/data/faculty_metrics.json
  backend/src/seed/seed_faculty_metrics.ts
  backend/src/seed/seed_users.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  docs/backend/api_calls.md
  docs/backend/test_api_calls.md
  frontend/__tests__/apiMethods.spec.ts
  frontend/api/WebService.ts
  frontend/api/apiMethods.ts
Labels: documentation, development

#13 Student List API Endpoint
  backend/README.md
  backend/__tests__/faculty-metrics.controller.spec.ts
  backend/__tests__/students.controller.spec.ts
  backend/__tests__/students.service.spec.ts
  backend/src/app.module.ts
  backend/src/entity/faculty_metric.entity.ts
  backend/src/main.ts
  backend/src/modules/faculty-metrics/faculty-metrics-default.ts
  backend/src/modules/faculty-metrics/faculty-metrics.controller.ts
  backend/src/modules/students/students.controller.ts
  backend/src/modules/students/students.module.ts
  backend/src/modules/students/students.service.ts
  backend/src/seed/data/applications.json
  backend/src/seed/seed_applications.ts
  docs/backend/api_calls.md
  frontend/api/WebService.ts
Labels: documentation, development, review needed

#16 Documents API
  .gitignore
  backend/__tests__/documents.controller.spec.ts
  backend/__tests__/documents.service.spec.ts
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/dto/create-document.dto.ts
  backend/src/entity/document.entity.ts
  backend/src/main.ts
  backend/src/modules/documents/document-type.enum.ts
  backend/src/modules/documents/documents.controller.ts
  backend/src/modules/documents/documents.module.ts
  backend/src/modules/documents/documents.service.ts
  backend/src/seed/data/documents.json
  backend/src/seed/seed_documents.ts
  docs/backend/api_calls.md
  docs/frontend/WebService.md
  frontend/__tests__/apiMethods.spec.ts
  frontend/__tests__/documentsApiMethods.spec.ts
  frontend/api/WebService.ts
  frontend/api/apiMethods.ts
  frontend/api/documentsApiMethods.ts
  frontend/app/(faculty)/studentList/application/studentPageContent.tsx
  frontend/components/ExcelViewer.tsx
  frontend/components/PdfViewer.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/types/ApplicationData.ts
  frontend/types/DocumentData.ts
  frontend/types/StudentData.ts
Labels: development, review needed

#17 Home Page Redesign
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/package-lock.json
  frontend/public/background_image.jpg
  package-lock.json
Labels: review needed

#15 Backend: Implement authentication structure
  backend/.env.example
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/dto/auth.dto.ts
  backend/src/entity/session.entity.ts
  backend/src/entity/student.entity.ts
  backend/src/entity/user.entity.ts
  backend/src/modules/auth/auth.controller.ts
  backend/src/modules/auth/auth.guard.ts
  backend/src/modules/auth/auth.module.ts
  backend/src/modules/auth/auth.service.ts
  backend/src/modules/students/students.controller.ts
  backend/src/seed/seedUsers.ts
  backend/src/seed/seed_users.ts
  backend/src/types/environment.d.ts
  backend/tsconfig.json
  docs/backend/auth_flow.md
Labels: review needed

#20 Migration Scripts and Documentation
  backend/package.json
  backend/src/database/data-source.ts
  backend/src/database/database.module.ts
  backend/src/database/migrations/1742868447437-SepMigration.ts
  backend/src/database/migrations/1742870212107-SepMigration.ts
  docs/backend/migrations.md
Labels: review needed

#23 Misc Improvements
  backend/__tests__/auth.controller.spec.ts
  backend/__tests__/auth.guard.spec.ts
  backend/__tests__/auth.service.spec.ts
  backend/__tests__/documents.controller.spec.ts
  backend/__tests__/http_exception.filter.spec.ts
  backend/__tests__/reviews.controller.spec.ts
  backend/__tests__/reviews.service.spec.ts
  backend/__tests__/test.controller.spec.ts
  backend/__tests__/test.service.spec.ts
  backend/package.json
  backend/src/app.module.ts
  backend/src/database/data-source.ts
  backend/src/database/database.module.ts
  backend/src/dto/update-review.dto.ts
  backend/src/main.ts
  backend/src/modules/reviews/reviews.controller.ts
  backend/src/modules/reviews/reviews.module.ts
  backend/src/modules/reviews/reviews.service.ts
  backend/src/modules/test/test.controller.ts
  backend/src/modules/test/test.module.ts
  backend/src/modules/test/test.service.ts
  backend/src/seed/data/reviews.json
  backend/src/seed/runSeedFunctions.ts
  backend/src/seed/seedTestTable.ts
  backend/src/seed/seed_applications.ts
  backend/src/seed/seed_documents.ts
  backend/src/seed/seed_faculty_metrics.ts
  backend/src/seed/seed_review_metrics.ts
  backend/src/seed/seed_reviews.ts
  backend/src/seed/seed_users.ts
  docs/backend/api_calls.md
  docs/commands.md
  frontend/api/WebService.ts
Labels: review needed
