Repository uiowaSEP2025/sep2025-project-team_006, pull requests merged in 2025-04, with the labels that each got.

#28 Jest Setup + Frontend Tests
  frontend/__tests__/components/card.spec.tsx
  frontend/__tests__/components/excelViewer.spec.tsx
  frontend/__tests__/components/pdfViewer.spec.tsx
  frontend/__tests__/home.spec.tsx
  frontend/__tests__/metricSetting.spec.tsx
  frontend/__tests__/styleMock.js
  frontend/api/WebService.ts
  frontend/api/apiMethods.ts
  frontend/api/documentsApiMethods.ts
  frontend/api/methods.ts
  frontend/app/(faculty)/faculty/page.tsx
  frontend/app/(faculty)/facultyHome/page.tsx
  frontend/app/(faculty)/metricSetting/page.tsx
  frontend/app/(faculty)/studentList/application/studentPageContent.tsx
  frontend/app/(faculty)/studentList/page.tsx
  frontend/app/(student)/createAccount/page.tsx
  frontend/app/(student)/studentHome/page.tsx
  frontend/app/(student)/students/page.tsx
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/app/test/page.tsx
  frontend/babel.config.test.js
  frontend/components/ExcelViewer.tsx
  frontend/components/HomeDashboard.tsx
  frontend/components/Login.tsx
  frontend/components/MetricForm.tsx
  frontend/components/PdfViewer.tsx
  frontend/components/ProfileList.tsx
  frontend/components/ReviewForm.tsx
  frontend/components/SignUp.tsx
  frontend/components/ui/button.tsx
  frontend/components/ui/card.tsx
  frontend/components/ui/command.tsx
  frontend/components/ui/dialog.tsx
  frontend/components/ui/input.tsx
  frontend/components/ui/label.tsx
  frontend/components/ui/popover.tsx
  frontend/components/ui/resizable.tsx
  frontend/components/ui/separator.tsx
  frontend/components/ui/sheet.tsx
  frontend/components/ui/sidebar.tsx
  frontend/components/ui/skeleton.tsx
  frontend/components/ui/tabs.tsx
  frontend/components/ui/textarea.tsx
  frontend/components/ui/tooltip.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/types/ApplicationData.ts
  frontend/types/DocumentData.ts
  frontend/types/StudentData.ts
Labels: testing

#32 Review Submission
  backend/__tests__/reviews.controller.spec.ts
  backend/__tests__/reviews.service.spec.ts
  backend/src/database/migrations/1743971321922-SubmitReview.ts
  backend/src/entity/review.entity.ts
  backend/src/modules/reviews-metrics/review-metrics.service.ts
  backend/src/modules/reviews/reviews.controller.ts
  backend/src/modules/reviews/reviews.service.ts
  docs/backend/api_calls.md
  frontend/api/WebService.ts
  frontend/app/(faculty)/facultyHome/page.tsx
  frontend/app/(faculty)/informationPage/page.tsx
  frontend/app/(faculty)/metricSetting/page.tsx
  frontend/app/(faculty)/reviewedApplicants/page.tsx
  frontend/app/(faculty)/studentList/application/studentPageContent.tsx
  frontend/app/(faculty)/studentList/page.tsx
  frontend/app/(student)/studentHome/page.tsx
  frontend/components/HomeDashboard.tsx
  frontend/components/Login.tsx
  frontend/components/MetricForm.tsx
  frontend/components/ui/command.tsx
Labels: review needed

#33 Review Templates
  backend/__tests__/review-metrics.controller.spec.ts
  backend/__tests__/review-metrics.service.spec.ts
  backend/__tests__/reviews.controller.spec.ts
  backend/__tests__/reviews.service.spec.ts
  backend/__tests__/templates.controller.spec.ts
  backend/__tests__/templates.service.spec.ts
  backend/package-lock.json
  backend/package.json
  backend/src/app.module.ts
  backend/src/database/data-source.ts
  backend/src/database/database.module.ts
  backend/src/database/migrations/1744159047145-TemplateMigration.ts
  backend/src/database/migrations/1744332306433-ReviewTemplateMigration.ts
  backend/src/dto/create-review-metric.dto.ts
  backend/src/dto/create-review.dto.ts
  backend/src/dto/create-template-metric.dto.ts
  backend/src/dto/create-template.dto.ts
  backend/src/dto/update-review-metric.dto.ts
  backend/src/dto/update-review.dto.ts
  backend/src/dto/update-template.dto.ts
  backend/src/entity/review.entity.ts
  backend/src/entity/review_metric.entity.ts
  backend/src/entity/template.entity.ts
  backend/src/entity/template_metric.entity.ts
  backend/src/main.ts
  backend/src/modules/reviews-metrics/review-metrics.controller.ts
  backend/src/modules/reviews-metrics/review-metrics.service.ts
  backend/src/modules/reviews/reviews.controller.ts
  backend/src/modules/reviews/reviews.module.ts
  backend/src/modules/reviews/reviews.service.ts
  backend/src/modules/templates/departments.enum.ts
  backend/src/modules/templates/templates.controller.ts
  backend/src/modules/templates/templates.module.ts
  backend/src/modules/templates/templates.servive.ts
  backend/src/seed/data/reviews.json
  backend/src/seed/data/templates.json
  backend/src/seed/documents/test_excel1.xlsx
  backend/src/seed/runSeedFunctions.ts
  backend/src/seed/seed_applications.ts
  backend/src/seed/seed_documents.ts
  backend/src/seed/seed_faculty_metrics.ts
  backend/src/seed/seed_review_metrics.ts
  backend/src/seed/seed_reviews.ts
  backend/src/seed/seed_templates.ts
  backend/src/seed/seed_users.ts
  docs/backend/api_calls.md
  frontend/__tests__/(faculty)/studentPageContent.spec.tsx
  frontend/__tests__/reviewForm.spec.tsx
  frontend/api/WebService.ts
  frontend/app/(faculty)/facultyHome/page.tsx
  frontend/app/(faculty)/studentList/application/studentPageContent.tsx
  frontend/app/(faculty)/templateSetting/page.tsx
  frontend/app/layout.tsx
  frontend/app/test/page.tsx
  frontend/components/ReviewForm.tsx
  frontend/types/MetricData.ts
Labels: review needed

#35 Add additional student registration fields
  backend/__tests__/auth.controller.spec.ts
  backend/__tests__/auth.service.spec.ts
  backend/src/dto/auth.dto.ts
  backend/src/modules/auth/auth.controller.ts
  backend/src/modules/auth/auth.service.ts
  docs/frontend/deployment_update.md
  frontend/app/(faculty)/metricSetting/page.tsx
  frontend/app/(faculty)/studentList/application/studentPageContent.tsx
  frontend/app/api/register/route.ts
  frontend/app/layout.tsx
  frontend/components/SignUp.tsx
  frontend/next.config.js
  frontend/types/window.d.ts
Labels: not ready for review

#36 Admin Role + Review Scores
  backend/__tests__/reviews.controller.spec.ts
  backend/__tests__/reviews.service.spec.ts
  backend/__tests__/util/calculate_faculty_score.spec.ts
  backend/__tests__/util/calculate_overall_score.spec.ts
  backend/src/database/migrations/1744758075254-isAdminMigration.ts
  backend/src/entity/faculty.entity.ts
  backend/src/modules/auth/auth.service.ts
  backend/src/modules/reviews/reviews.controller.ts
  backend/src/modules/reviews/reviews.service.ts
  backend/src/seed/data/faculty.json
  backend/src/seed/seed_users.ts
  backend/src/util/calculate_faculty_score.ts
  backend/src/util/calculate_overall_score.ts
  frontend/app/(faculty)/templateSetting/page.tsx
Labels: review needed

#37 Community testing
  frontend/__tests__/(faculty)/informationPage.spec.tsx
  frontend/__tests__/(faculty)/metricSettings.spec.tsx
  frontend/__tests__/(faculty)/studentList.spec.tsx
  frontend/__tests__/(faculty)/templateSettings.spec.tsx
  frontend/__tests__/(student)/studentHome.spec.tsx
  frontend/__tests__/(student)/students.spec.tsx
  frontend/__tests__/apiMethods.spec.ts
  frontend/__tests__/documentsApiMethods.spec.ts
  frontend/app/(faculty)/informationPage/page.tsx
  frontend/app/(faculty)/metricSetting/page.tsx
  frontend/app/(faculty)/studentList/page.tsx
  frontend/app/(faculty)/templateSetting/page.tsx
  frontend/app/(student)/studentHome/page.tsx
  frontend/app/(student)/students/page.tsx
  frontend/package.json
Labels: review needed
